### ISSUE TITLE
Can't install rollout

### ISSUE THREAD

**Issue by scorpiozj** [rollout/rollout.io-ios#24]
can't install rollout and the error part of the log:  
    
 ```Rollout: extracting file 33 of 34
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `encode': "\xE7" on US-ASCII (Encoding::InvalidByteSequenceError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `initialize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'
	from /Users/zhuj/Desktop/untitled folder/ZZFlashSD/Pods/Rollout.io/lib/create_dynamic_swizzler.rb:171:in `<main>'
Command /bin/sh failed with exit code 3```
I use pod to install the rollout, and when I build it, the error happens.    
The environment :
* Xcode 6.1.1, Mac OS X 10.10.2
* ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

**Comment by scorpiozj** [comment]
I just add the following to the `create_dynamic_swizzler.rb`:
```Encoding.default_external = Encoding::UTF_8```

and then it build and run successfully.  
PS: 
following: [https://github.com/jimmycuadra/lita-hipchat/issues/3](https://github.com/jimmycuadra/lita-hipchat/issues/3)

**Comment by AlbertoRoomi** [comment]
I open the create_dynamic_swizzler.rb but where does the encoding text goes?
