### ISSUE TITLE
Ruby version error when Bundler is used

### ISSUE THREAD

**Issue by bfcatch** [rollout/rollout.io-ios#77]
In our project setup, we use rvm/bundler to manage versions of ruby and gems
And currently we use ruby version 2.1.2 in the Gem file. When our CI machine builds the project with these steps:

```
# use ruby 2.1.2 and the dev gemset
rvm use 2.1.2@dev

bundle install

cd ${WORKSPACE}/TheProject

# kick off build with fastlane
fastlane ios adhoc

# switch back to the default ruby
rvm use default
```

Below error occurs:

```
    /bin/sh -c /Users/ciuser/Workspace/Jenkins/job1/TheApp/Build/Intermediates/ArchiveIntermediates/TheTarget/IntermediateBuildFilesPath/TheApp.build/Release-iphoneos/TheTarget.build/Script-C8E2E324E9A34553BD1C14B3.sh
/Users/ciuser/.rvm/gems/ruby-2.1.2@dev/gems/bundler-1.10.6/lib/bundler/definition.rb:412:in `validate_ruby!': Your Ruby version is 2.0.0, but your Gemfile specified 2.1.2 (Bundler::RubyVersionMismatch)
        from /Users/ciuser/.rvm/gems/ruby-2.1.2@dev/gems/bundler-1.10.6/lib/bundler.rb:123:in `setup'
        from /Users/ciuser/.rvm/gems/ruby-2.1.2@dev/gems/bundler-1.10.6/lib/bundler/setup.rb:18:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Rollout post compile script
Rollout: going to generate structure and code
Rollout: using dsym generated by Xcode: "/Users/ciuser/Workspace/Jenkins/job1/TheApp/Build/Intermediates/ArchiveIntermediates/TheTarget/BuildProductsPath/Release-iphoneos/COTDPreprod.app.dSYM/Contents/Resources/DWARF/COTDPreprod"
/Users/ciuser/.rvm/gems/ruby-2.1.2@dev/gems/bundler-1.10.6/lib/bundler/definition.rb:412:in `validate_ruby!': Your Ruby version is 2.0.0, but your Gemfile specified 2.1.2 (Bundler::RubyVersionMismatch)
        from /Users/ciuser/.rvm/gems/ruby-2.1.2@dev/gems/bundler-1.10.6/lib/bundler.rb:123:in `setup'
        from /Users/ciuser/.rvm/gems/ruby-2.1.2@dev/gems/bundler-1.10.6/lib/bundler/setup.rb:18:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

Can Rollout.io scripts be more rvm/bundler friendly please?

**Comment by ekeren** [comment]
We no longer have ruby in our code - functionality moved to swift/objc executables
